name: Build & Release HK POS (Windows)

on:
  push:
    tags:
      - 'v*.*.*'   # runs when you push a tag like v1.0.2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Use npm install (not npm ci) because your repo doesn't have package-lock.json
      - name: Install dependencies
        run: npm install --no-audit --no-fund

      # Rebuild any native modules (better-sqlite3, escpos-usb) for Electron
      - name: Rebuild native modules for Electron
        run: npx electron-builder install-app-deps

      - name: Build Windows installer
        run: npx electron-builder --win --x64

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: hkpos-dist
          path: dist/**

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hkpos-dist
          path: dist

      - name: Get tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          name: HK POS ${{ steps.tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap
