name: Build & Release HK POS (Windows)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build Windows installer
        run: npx electron-builder --win --x64
      - name: Upload artifact (for Release)
        uses: actions/upload-artifact@v4
        with:
          name: hkpos-dist
          path: dist/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hkpos-dist
          path: dist
      - name: Get tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          name: HK POS ${{ steps.tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap
